# Generated by Django 4.1.1 on 2022-10-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_remove_receta_foto_fotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
    ]
