# Generated by Django 4.1.1 on 2022-10-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_rename_fotos_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
