# Generated by Django 4.1.1 on 2022-10-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_foto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='nombre',
        ),
    ]
