# Generated by Django 4.1.1 on 2022-10-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_remove_foto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
