# Generated by Django 4.1.1 on 2022-11-24 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_alter_receta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.FileField(upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidades',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='receta',
            name='preparación',
            field=models.TextField(max_length=5000, validators=[django.core.validators.RegexValidator('[A-Z]*', message='El texto debe empezar por mayúscula')]),
        ),
    ]
