# Generated by Django 4.1.1 on 2022-11-24 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_alter_foto_foto_alter_ingrediente_unidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='preparación',
            field=models.TextField(max_length=5000, validators=[django.core.validators.RegexValidator(code='invalid_preparacion', message='El texto debe empezar por mayúscula', regex='[A-Z]*')]),
        ),
    ]
