# Generated by Django 4.1.1 on 2022-11-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_alter_receta_preparación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='preparación',
            new_name='preparacion',
        ),
    ]
