# Generated by Django 4.1.1 on 2022-11-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0011_rename_preparación_receta_preparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(max_length=5000),
        ),
    ]
