# Generated by Django 4.1.1 on 2022-11-24 17:52

from django.db import migrations, models
import recetas.models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0012_alter_receta_preparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(max_length=5000, validators=[recetas.models.validateFirstCapital]),
        ),
    ]
