# Generated by Django 4.1.1 on 2022-11-24 18:13

from django.db import migrations, models
import recetas.models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0013_alter_receta_preparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, validators=[recetas.models.validateFirstCapital]),
        ),
    ]
